### ISSUE TITLE
Fix breaking changes from updating Strum dependency

### ISSUE THREAD

**Issue by tjtelan** [tjtelan/git-url-parse-rs#14]
PR #13 revealed that there's a breaking change when updating the version specifier on the strum dependency.

* [ ] Update Cargo.toml : `strum` + `strum_macros` to `^0.20`
* [ ] Fix code break from Cargo.toml changes
* [ ] Bump crate version to `0.3.1` (minor version change)

**Comment by tjtelan** [comment]
I didn't experience any build failures when updating the strum versions to `^0.20`, and the Github Actions CI run seems to have passed. I don't see any obvious reasons to consider not call this fixed. I'll add some notes to the changelog and publish this crate.

**Comment by EverlastingBugstopper** [comment]
> I didn't experience any build failures when updating the strum versions to ^0.20

ah! i think i was attempting to do too much by removing `strum_macros` and importing them via `strum = { features = ["derive"] }` - makes sense that just updating the versions by themselves works fine 😄 thanks for cutting this release!

**Comment by tjtelan** [comment]
Coincidentally I also had a local build failure with `strum` imports initially when I wrote up this issue. But it seemed to be cache related, because I couldn't reproduce the failure after a `cargo clean`.
