### ISSUE TITLE
Less dependencies?

### ISSUE THREAD

**Issue by milesj** [tjtelan/git-url-parse-rs#52]
Thanks for this lib. I got tired of trying to support all the variants myself.

With that said, it would be nice if this lib had less dependencies. For context, I try and keep our binaries lean, but this pulls in eyre and strum, which then pulls in more stuff. We don't use eyre but now it's a part of the build. 

Would be nice to be able to not have this. I know how much work managing Rust libs is, so at minimum, maybe these can be behind a feature flag?

**Comment by tjtelan** [comment]
Sorry, got really busy and didn't see this issue until now

I plan to address this soon! I wrote this crate to learn Rust and the dependency bloat is leftover early learner mistakes
